//! ECMA-402 / Intl build tier — compile-time gate (`build_options.intl`).
//!
//! Distinct from CLI verbs (`--enable=`, `--allow=`, `--unhardened`): Intl is
//! a **build flavour** (ROADMAP: default edge/server build omits the locale
//! stack; an Intl-enabled build is opt-in), not a runtime capability or a
//! pre-Stage-4 proposal.
//!
//! | Tier | `Intl` global | Temporal calendars / IANA | Data |
//! |------|---------------|---------------------------|------|
//! | `off`  | absent | ISO + UTC/offset only | none |
//! | `stub` | structural ECMA-402 (option validation, stubs) | accept ids/names; ISO/UTC math | none |
//! | `full` | structural ECMA-402 | real IANA offsets via embedded tzdb | `vendor/tzdata/cynic_tzdb.bin` |
//!
//! Build: `zig build -Dintl=off|stub|full` (default `off`).
//!
//! The tier type lives in `build_options` (generated by `build.zig`); we
//! only expose predicates so call sites don't fight two `IntlTier` types.

const build_options = @import("build_options");

/// True when the `Intl` namespace is installed at realm init.
pub const enabled: bool = switch (build_options.intl) {
    .off => false,
    .stub, .full => true,
};

/// True when Temporal accepts non-ISO calendar ids and structural IANA
/// zone names (stub/full). When off, only ISO + UTC/offset (ROADMAP
/// shipped Temporal scope).
pub const temporal_intl_extras: bool = enabled;

/// True when embedded tzdata is consulted for named IANA zones
/// (`getOffsetNanosecondsFor` / zone-id acceptance). `full` only;
/// calendars/formatters still share the structural stub surface.
pub const has_locale_data: bool = build_options.intl == .full;
