//! UAX #29 default text segmentation — extended grapheme cluster (§3.1.1)
//! and word (§4.1.1) boundaries over WTF-8 bytes, backing Intl.Segmenter.
//!
//! Classes are derived from the generated Unicode property tables
//! (`src/unicode/property_tables.zig`, regenerated by `zig build
//! gen-unicode`): Grapheme_Extend, Extended_Pictographic, Alphabetic,
//! Ideographic, the Mc/Nd/Zs/Pc/Cf general categories, and the Katakana /
//! Hiragana scripts. Hangul syllable classes come from the fixed Jamo
//! ranges plus LV/LVT arithmetic on the precomposed block. Lone surrogates
//! decode to their code points and fall into the default break-around
//! class, so hostile WTF-8 input segments without any error path.

const std = @import("std");
const props = @import("../unicode/properties.zig");
const utf16 = @import("utf16.zig");

const bp_gext = props.binaryProperty("Grapheme_Extend").?;
const bp_extpic = props.binaryProperty("Extended_Pictographic").?;
const bp_alpha = props.binaryProperty("Alphabetic").?;
const bp_ideo = props.binaryProperty("Ideographic").?;
const gc_mc = props.generalCategory("Mc").?;
const gc_nd = props.generalCategory("Nd").?;
const gc_zs = props.generalCategory("Zs").?;
const gc_pc = props.generalCategory("Pc").?;
const gc_cf = props.generalCategory("Cf").?;
const gc_cc = props.generalCategory("Cc").?;
const sc_kata = props.script("Katakana").?;
const sc_hira = props.script("Hiragana").?;

/// Total WTF-8 decode: valid UTF-8 sequences decode normally; the CESU-8
/// surrogate escapes (and any truncated tail) yield a code point without
/// erroring.
fn decode(bytes: []const u8, i: usize) struct { cp: u21, len: usize } {
    const len = utf16.utf8SeqLen(bytes[i]);
    if (i + len > bytes.len) return .{ .cp = bytes[i], .len = 1 };
    const cp: u21 = switch (len) {
        1 => bytes[i],
        2 => (@as(u21, bytes[i] & 0x1F) << 6) | (bytes[i + 1] & 0x3F),
        3 => (@as(u21, bytes[i] & 0x0F) << 12) | (@as(u21, bytes[i + 1] & 0x3F) << 6) | (bytes[i + 2] & 0x3F),
        else => (@as(u21, bytes[i] & 0x07) << 18) | (@as(u21, bytes[i + 1] & 0x3F) << 12) | (@as(u21, bytes[i + 2] & 0x3F) << 6) | (bytes[i + 3] & 0x3F),
    };
    return .{ .cp = cp, .len = len };
}

// ── Grapheme cluster boundaries (UAX #29 §3.1.1, GB1-GB999) ─────────────────

const GB = enum { other, cr, lf, control, extend, zwj, spacing_mark, l, v, t, lv, lvt, ext_pic, ri };

fn gbClass(cp: u21) GB {
    return switch (cp) {
        0x0D => .cr,
        0x0A => .lf,
        0x200D => .zwj,
        0x1F1E6...0x1F1FF => .ri,
        0x1100...0x115F, 0xA960...0xA97C => .l,
        0x1160...0x11A7, 0xD7B0...0xD7C6 => .v,
        0x11A8...0x11FF, 0xD7CB...0xD7FB => .t,
        0xAC00...0xD7A3 => if ((cp - 0xAC00) % 28 == 0) GB.lv else GB.lvt,
        else => {
            // Emoji_Modifier (skin tones) is Extend in GraphemeBreakProperty.
            if (props.rangeContains(bp_gext, cp) or (cp >= 0x1F3FB and cp <= 0x1F3FF)) return .extend;
            if (props.rangeContains(bp_extpic, cp)) return .ext_pic;
            if (props.rangeContains(gc_mc, cp)) return .spacing_mark;
            if (cp == 0x2028 or cp == 0x2029) return .control; // Zl / Zp
            if (props.rangeContains(gc_cc, cp) or props.rangeContains(gc_cf, cp)) return .control;
            return .other;
        },
    };
}

/// Byte offset one past the extended grapheme cluster starting at `start`.
pub fn graphemeEnd(bytes: []const u8, start: usize) usize {
    const first = decode(bytes, start);
    var i = start + first.len;
    var prev = gbClass(first.cp);
    // GB3 CR × LF; GB4 break after (Control | CR | LF).
    if (prev == .cr and i < bytes.len and bytes[i] == 0x0A) return i + 1;
    if (prev == .cr or prev == .lf or prev == .control) return i;
    // GB11 state: ExtPic Extend* ZWJ × ExtPic. GB12/13: pair up regional
    // indicators (a flag is exactly two).
    var pic_run = prev == .ext_pic;
    var zwj_after_pic = false;
    var ri_open = prev == .ri;
    while (i < bytes.len) {
        const d = decode(bytes, i);
        const cur = gbClass(d.cp);
        const join = switch (cur) {
            .extend, .zwj => true, // GB9
            .spacing_mark => true, // GB9a
            .cr, .lf, .control => false, // GB5
            .l, .lv, .lvt => prev == .l, // GB6
            .v => prev == .l or prev == .lv or prev == .v, // GB6/GB7
            .t => prev == .lv or prev == .v or prev == .lvt or prev == .t, // GB7/GB8
            .ext_pic => zwj_after_pic, // GB11
            .ri => ri_open, // GB12/GB13
            .other => false, // GB999
        };
        if (!join) return i;
        if (cur == .ri) {
            ri_open = !ri_open;
        } else if (cur != .extend and cur != .zwj) {
            ri_open = false;
        }
        switch (cur) {
            .zwj => zwj_after_pic = pic_run,
            .extend => zwj_after_pic = false, // Extend after ZWJ ends the GB11 chain
            else => {
                pic_run = cur == .ext_pic;
                zwj_after_pic = false;
            },
        }
        if (cur != .extend and cur != .zwj) prev = cur;
        i += d.len;
    }
    return bytes.len;
}

// ── Word boundaries (UAX #29 §4.1.1, WB1-WB999) ─────────────────────────────

const WB = enum { other, cr, lf, newline, zwj, extend, format, wsegspace, aletter, mid_letter, mid_num, mid_numlet, single_quote, double_quote, numeric, katakana, extendnumlet, ext_pic, ri };

fn wbClass(cp: u21) WB {
    return switch (cp) {
        0x0D => .cr,
        0x0A => .lf,
        0x0B, 0x0C, 0x85, 0x2028, 0x2029 => .newline,
        0x200D => .zwj,
        0x1F1E6...0x1F1FF => .ri,
        0x27 => .single_quote,
        0x22 => .double_quote,
        0x3A, 0xB7, 0x0387, 0x055F, 0x05F4, 0x2027, 0xFE13, 0xFE55, 0xFF1A => .mid_letter,
        0x2C, 0x3B, 0x37E, 0x589, 0x60C, 0x60D, 0x66C, 0x7F8, 0x2044, 0xFE10, 0xFE14, 0xFE50, 0xFE54, 0xFF0C, 0xFF1B => .mid_num,
        0x2E, 0x2018, 0x2019, 0x2024, 0xFE52, 0xFF07, 0xFF0E => .mid_numlet,
        0x5F => .extendnumlet,
        else => {
            if (props.rangeContains(bp_gext, cp) or props.rangeContains(gc_mc, cp) or (cp >= 0x1F3FB and cp <= 0x1F3FF)) return .extend;
            if (props.rangeContains(gc_zs, cp)) return .wsegspace;
            if (props.rangeContains(gc_nd, cp)) return .numeric;
            if (props.rangeContains(gc_pc, cp)) return .extendnumlet;
            if (props.rangeContains(sc_kata, cp)) return .katakana;
            if (props.rangeContains(bp_alpha, cp) and
                !props.rangeContains(bp_ideo, cp) and
                !props.rangeContains(sc_hira, cp)) return .aletter;
            if (props.rangeContains(bp_extpic, cp)) return .ext_pic;
            if (props.rangeContains(gc_cf, cp)) return .format;
            return .other;
        },
    };
}

/// Byte offset of the next base (non-Extend/Format/ZWJ) code point at or
/// after `i`, per WB4; `null` when only absorbable code points remain.
fn nextBaseClass(bytes: []const u8, i: usize) ?WB {
    var j = i;
    while (j < bytes.len) {
        const d = decode(bytes, j);
        const c = wbClass(d.cp);
        if (c != .extend and c != .format and c != .zwj) return c;
        j += d.len;
    }
    return null;
}

/// Byte offset one past the word segment starting at `start`.
pub fn wordEnd(bytes: []const u8, start: usize) usize {
    const first = decode(bytes, start);
    var i = start + first.len;
    var prev = wbClass(first.cp);
    // WB3 CR × LF; WB3a break after Newline | CR | LF.
    if (prev == .cr and i < bytes.len and bytes[i] == 0x0A) return i + 1;
    if (prev == .cr or prev == .lf or prev == .newline) return i;
    var ri_open = prev == .ri; // WB15/16 pairing state
    while (i < bytes.len) {
        const d = decode(bytes, i);
        const cur = wbClass(d.cp);
        // WB3c ZWJ × ExtPic (checked before the WB4 absorb).
        if (cur == .zwj) {
            const j = i + d.len;
            if (j < bytes.len) {
                const dn = decode(bytes, j);
                if (wbClass(dn.cp) == .ext_pic) {
                    i = j + dn.len;
                    prev = .ext_pic;
                    continue;
                }
            }
            i += d.len; // WB4
            continue;
        }
        if (cur == .extend or cur == .format) {
            i += d.len; // WB4 — absorbed; prev keeps its class
            continue;
        }
        if (cur == .cr or cur == .lf or cur == .newline) break; // WB3b
        const join = switch (cur) {
            .wsegspace => prev == .wsegspace, // WB3d
            .aletter => prev == .aletter or prev == .numeric or prev == .extendnumlet, // WB5/WB10/WB13b
            .numeric => prev == .numeric or prev == .aletter or prev == .extendnumlet, // WB8/WB9/WB13b
            .katakana => prev == .katakana or prev == .extendnumlet, // WB13/WB13b
            .extendnumlet => prev == .aletter or prev == .numeric or prev == .katakana or prev == .extendnumlet, // WB13a
            // WB6/WB7: AHLetter × (MidLetter | MidNumLet | ') AHLetter.
            .mid_letter => prev == .aletter and nextBaseClass(bytes, i + d.len) == .aletter,
            // WB11/WB12: Numeric × (MidNum | MidNumLet | ') Numeric.
            .mid_num => prev == .numeric and nextBaseClass(bytes, i + d.len) == .numeric,
            .mid_numlet, .single_quote => (prev == .aletter and nextBaseClass(bytes, i + d.len) == .aletter) or
                (prev == .numeric and nextBaseClass(bytes, i + d.len) == .numeric),
            .ri => prev == .ri and ri_open, // WB15/WB16
            else => false, // WB999
        };
        if (!join) break;
        ri_open = cur == .ri and !ri_open;
        switch (cur) {
            .mid_letter, .mid_num, .mid_numlet, .single_quote => {}, // prev stays the letter/number class
            else => prev = cur,
        }
        i += d.len;
    }
    return i;
}

/// §18.7.1 isWordLike — the segment contains a letter, digit, kana, or
/// ideograph (dictionary-segmented scripts count as words in ICU).
pub fn segmentIsWordLike(bytes: []const u8) bool {
    var i: usize = 0;
    while (i < bytes.len) {
        const d = decode(bytes, i);
        switch (wbClass(d.cp)) {
            .aletter, .numeric, .katakana, .extendnumlet => return true,
            else => {
                if (props.rangeContains(bp_ideo, d.cp) or props.rangeContains(sc_hira, d.cp)) return true;
            },
        }
        i += d.len;
    }
    return false;
}

test "uax29: grapheme clusters" {
    // Hangul Jamo compositions stay single clusters.
    try std.testing.expectEqual(@as(usize, 6), graphemeEnd("\u{1102}\u{1162}", 0));
    // Combining mark attaches; emoji ZWJ sequence is one cluster.
    try std.testing.expectEqual(@as(usize, 3), graphemeEnd("e\u{0301}x", 0));
    const wave = "\u{1F44B}\u{1F3FB}";
    try std.testing.expectEqual(wave.len, graphemeEnd(wave, 0));
    // CR LF is one cluster; control breaks.
    try std.testing.expectEqual(@as(usize, 2), graphemeEnd("\r\nx", 0));
}

test "uax29: word boundaries" {
    // Numeric with MidNumLet stays one word; space run separate.
    try std.testing.expectEqual(@as(usize, 4), wordEnd("1.23 x", 0));
    try std.testing.expectEqual(@as(usize, 5), wordEnd("don't x", 0));
    // Ideographs break from each other (WB999) and from spaces.
    const han = "台台";
    try std.testing.expectEqual(@as(usize, 3), wordEnd(han, 0));
    try std.testing.expectEqual(@as(usize, 1), wordEnd(" 台", 0));
}
