#!/usr/bin/env bash
# Compile vendored IANA tzdata *sources* (vendor/tzdata/iana/) into a zoneinfo
# tree with system `zic`, then invoke tools/pack_tzdata.zig on that tree.
#
# Called by `zig build pack-tzdata`. Not usually run directly; prefer
# `tools/fetch-tzdata.sh` to refresh sources from the network first.
#
# Usage:
#   tools/compile-iana-tzdata.sh <pack_tzdata_exe> <repo_root>

set -euo pipefail

PACK_EXE="${1:?pack_tzdata executable path}"
REPO_ROOT="${2:?repo root}"

IANA_DIR="$REPO_ROOT/vendor/tzdata/iana"
TZCODE_DIR="$REPO_ROOT/vendor/tzdata/tzcode"
OUT_BIN="$REPO_ROOT/vendor/tzdata/cynic_tzdb.bin"
OUT_VER="$REPO_ROOT/vendor/tzdata/VERSION"

# Build `zic` from vendored tzcode sources without invoking the full IANA
# Makefile (which expects tzdata region files alongside tzcode).
build_vendored_zic() {
    local tzcode_dir="$1"
    local ver="$2"
    local log="$3"
    local cc="${CC:-cc}"

    {
        echo "/* generated by compile-iana-tzdata.sh */"
        echo '#ifndef TZDEFAULT'
        echo '# define TZDEFAULT "/etc/localtime"'
        echo '#endif'
        echo '#ifndef TZDIR'
        echo '# define TZDIR "/usr/share/zoneinfo"'
        echo '#endif'
    } >"$tzcode_dir/tzdir.h"

    {
        echo "/* generated by compile-iana-tzdata.sh for IANA ${ver} */"
        echo 'static char const PKGVERSION[]="(tzcode) ";'
        echo "static char const TZVERSION[]=\"${ver}\";"
        echo 'static char const REPORT_BUGS_TO[]="tz@iana.org";'
    } >"$tzcode_dir/version.h"

    # Drop any stale binary/objects from a previous host build.
    rm -f "$tzcode_dir/zic" "$tzcode_dir/zic.o"

    if ! (
        cd "$tzcode_dir"
        "$cc" -O2 -std=c99 -Wall -Wextra -Wno-unused-parameter \
            -o zic zic.c
    ) >"$log" 2>&1; then
        return 1
    fi
    [[ -x "$tzcode_dir/zic" ]]
}

if [[ ! -d "$IANA_DIR" ]]; then
    echo "compile-iana-tzdata: missing $IANA_DIR" >&2
    echo "compile-iana-tzdata: fetch sources first: tools/fetch-tzdata.sh [--no-pack]" >&2
    exit 1
fi

if [[ ! -f "$IANA_DIR/africa" ]]; then
    echo "compile-iana-tzdata: $IANA_DIR does not look like an IANA tzdata source tree" >&2
    exit 1
fi

VERSION="unknown"
if [[ -f "$IANA_DIR/version" ]]; then
    VERSION="$(tr -d '[:space:]' <"$IANA_DIR/version")"
fi

WORK="$(mktemp -d "${TMPDIR:-/tmp}/cynic-zoneinfo.XXXXXX")"
cleanup() { rm -rf "$WORK"; }
trap cleanup EXIT

ZIC_OUT="$WORK/zoneinfo"
mkdir -p "$ZIC_OUT"

# Prefer a zic built from the vendored tzcode tarball (same IANA release as
# the sources). Host zic is often years old and emits only ~100 transitions
# that stop ~2007, so post-2007 instants mis-resolve without the POSIX footer.
ZIC_BIN=""
if [[ -d "$TZCODE_DIR" && -f "$TZCODE_DIR/zic.c" ]]; then
    echo "compile-iana-tzdata: building zic from vendor/tzdata/tzcode (IANA $VERSION)"
    # tzcode's Makefile wants a `version` file and generated headers; the
    # tarball does not include `version` (it lives in the tzdata tarball).
    if [[ ! -f "$TZCODE_DIR/version" && -f "$IANA_DIR/version" ]]; then
        cp "$IANA_DIR/version" "$TZCODE_DIR/version"
    fi
    # Build only `zic` — do not run the full default target (it wants the
    # tzdata region files next to tzcode). Generate headers the Makefile
    # would, then compile zic.c directly so we don't depend on make's
    # VERSION_DEPS chain (`africa` etc.).
    if build_vendored_zic "$TZCODE_DIR" "$VERSION" "$WORK/zic-build.log"; then
        ZIC_BIN="$TZCODE_DIR/zic"
    else
        echo "compile-iana-tzdata: warning: vendored zic build failed; see $WORK/zic-build.log" >&2
        cat "$WORK/zic-build.log" >&2 || true
    fi
fi
if [[ -z "$ZIC_BIN" ]]; then
    if command -v zic >/dev/null 2>&1; then
        ZIC_BIN="$(command -v zic)"
        echo "compile-iana-tzdata: falling back to system zic ($ZIC_BIN) — future DST may be wrong if zic is old"
    else
        echo "compile-iana-tzdata: no zic available (vendor tzcode build failed and no system zic)" >&2
        exit 1
    fi
fi

# Region files zic expects (order doesn't matter). `backward` supplies
# deprecated aliases (US/Eastern, etc.) that some tests still use.
REGION_FILES=(
    africa antarctica asia australasia europe
    northamerica southamerica etcetera factory backward
)

args=()
for f in "${REGION_FILES[@]}"; do
    if [[ -f "$IANA_DIR/$f" ]]; then
        args+=("$IANA_DIR/$f")
    fi
done

if [[ ${#args[@]} -eq 0 ]]; then
    echo "compile-iana-tzdata: no region files under $IANA_DIR" >&2
    exit 1
fi

echo "compile-iana-tzdata: $ZIC_BIN -d <tmp> (${#args[@]} source files, IANA $VERSION)"
"$ZIC_BIN" -d "$ZIC_OUT" "${args[@]}"

# Write a +VERSION in the zoneinfo tree so the packer can stamp it.
printf '%s\n' "$VERSION" >"$ZIC_OUT/+VERSION"

echo "compile-iana-tzdata: packing $ZIC_OUT -> $OUT_BIN"
"$PACK_EXE" --zoneinfo-root "$ZIC_OUT" -o "$OUT_BIN" --version-file "$OUT_VER"

# Augment VERSION with IANA provenance (packer writes basic stamp; rewrite richer).
BYTES=0
[[ -f "$OUT_BIN" ]] && BYTES="$(wc -c <"$OUT_BIN" | tr -d ' ')"
cat >"$OUT_VER" <<EOF
${VERSION}
# IANA tzdata source: vendor/tzdata/iana/ (release ${VERSION})
# IANA tzcode (zic):  vendor/tzdata/tzcode/ (release ${VERSION})
# Upstream: https://data.iana.org/time-zones/releases/tzdata${VERSION}.tar.gz
#           https://data.iana.org/time-zones/releases/tzcode${VERSION}.tar.gz
# Fetch:    tools/fetch-tzdata.sh ${VERSION}
# Pack:     zig build pack-tzdata  (make zic in tzcode + tools/pack_tzdata.zig)
# cynic_tzdb.bin bytes=${BYTES}
EOF

echo "compile-iana-tzdata: done (IANA ${VERSION}, ${BYTES} bytes)"
